### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by minuq**
Philosophical change mostly. Since we're assuming the env variables to be set more often than not, we can shorten the code without losing functionality and (arguably) improving readability, by using a try/except clause instead of checking each variable individually to be not set.

### CODE REVIEW

**Review by mylesagray — DISMISSED** [review]
LGTM

**Comment by KarlJGray** [comment]
I removed the requirement for signed commits on the `master` branch but in the branch protection rules the branch is also locked so no one can push to it @mylesagray. Do you want me to just remove the locked branch protection?

**Comment by minuq** [comment]
I like the requirement tbqh. I just forgot to sign the first commit.

**Comment by KarlJGray** [comment]
> I like the requirement tbqh. I just forgot to sign the first commit.

Cool, I've re-enabled the requirement for signed commits but will remove the locked branch

**Comment by mylesagray** [comment]
@minuq I think you'll need to do a commit squash and sign it for the PR to merge

**Review by mylesagray — APPROVED** [review]
LGTM

**Pull request merged**
